config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'tweets#index'
  resources :tweets
  resources :profiles, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if:  :devise_controller?
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
  end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)
     if @tweet.save
       redirect_to tweets_path
     else
       render :new
     end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweets_path
    else
      render :edit
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path
  end

private
def tweet_params
  params.require(:tweet).permit(:body)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTwitterClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/profiles/show.html.erb
<h1>Here are <%= @user.first_name %>'s tweets.</h1>
<table>
  <tr>
    <th>Messages</th>
    <th>Actions</th>
    <tr>
      <% @tweets.each do |tweet| %>
      <td><%= tweet.body %> </td>
      <td><%= link_to 'Show', tweet_path(tweet.id) %></td>
      <td><%= link_to 'Edit', edit_tweet_path(tweet.id)%></td>
      <td><%= link_to 'Delete', tweet_path(tweet.id), method: :delete %></td>
    </tr>
  </tr>
  <% end %>
</table>
<%= link_to 'Back', tweets_path%>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= simple_form_for @tweet, method: :patch do |f| %>
  <%= f.input :body %>
  <%= f.button :submit %>
<% end %>
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Tweets</h1>

<table>
  <tr>
    <th>Messages</th>
    <th>Actions</th>
    <tr>
      <% @tweets.each do |tweet| %>
      <td><%= tweet.body %> </td>
      <td><%= link_to 'Show', tweet_path(tweet.id) %></td>
      <td><%= link_to 'Edit', edit_tweet_path(tweet.id)%></td>
      <td><%= link_to 'Delete', tweet_path(tweet.id), method: :delete %></td>
    </tr>
  </tr>
  <% end %>
</table> <br>
<%= link_to 'Add New', new_tweet_path%>
<%= link_to 'Sign-out', destroy_user_session_path, method: :delete %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= simple_form_for @tweet do |f| %>
  <%= f.input :body %>
  <%= f.button :submit %>
<% end %>
<%= link_to 'Back', tweets_path%>

app/views/tweets/show.html.erb
<h2>user: <%=link_to @tweet.user.first_name, profile_path(@tweet.user.id) %></h2>

<%= @tweet.body %><br>
<%= link_to 'Back', tweets_path%>